version: '3.8'

services:
  app:
    build: .
    container_name: task-manager-app
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm start
